// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: status.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Status {
  public static partial class Status
  {
    static readonly string __ServiceName = "status.Status";

    static readonly grpc::Marshaller<global::Status.StatusRequest> __Marshaller_status_StatusRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Status.StatusRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Status.StatusResponse> __Marshaller_status_StatusResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Status.StatusResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Status.StatusRequest, global::Status.StatusResponse> __Method_GetStatus = new grpc::Method<global::Status.StatusRequest, global::Status.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStatus",
        __Marshaller_status_StatusRequest,
        __Marshaller_status_StatusResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Status.StatusReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Status</summary>
    [grpc::BindServiceMethod(typeof(Status), "BindService")]
    public abstract partial class StatusBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Status.StatusResponse> GetStatus(global::Status.StatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Status</summary>
    public partial class StatusClient : grpc::ClientBase<StatusClient>
    {
      /// <summary>Creates a new client for Status</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StatusClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Status that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StatusClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StatusClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StatusClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Status.StatusResponse GetStatus(global::Status.StatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Status.StatusResponse GetStatus(global::Status.StatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStatus, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Status.StatusResponse> GetStatusAsync(global::Status.StatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Status.StatusResponse> GetStatusAsync(global::Status.StatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStatus, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StatusClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StatusClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StatusBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetStatus, serviceImpl.GetStatus).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StatusBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Status.StatusRequest, global::Status.StatusResponse>(serviceImpl.GetStatus));
    }

  }
}
#endregion
